From node:20

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .
RUN cd client && npm run build

RUN npx prisma generate

EXPOSE 3000

# CMD [ "npm", "run", "dev" ]

CMD [ "npm", "start" ]
